// <auto-generated />
using System;
using Dot.Net.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApi.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20231020073907_add basic crud")]
    partial class addbasiccrud
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.BidModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account");

                    b.Property<double>("ask");

                    b.Property<double>("askQuantity");

                    b.Property<double>("bid");

                    b.Property<double>("bidQuantity");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("WebApi.Models.CurvePointModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("asOfDate");

                    b.Property<DateTime>("creationDate");

                    b.Property<int>("cureveId");

                    b.Property<double>("term");

                    b.Property<double>("value");

                    b.HasKey("ID");

                    b.ToTable("CurvePoint");
                });

            modelBuilder.Entity("WebApi.Models.RatingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fitchRaing");

                    b.Property<string>("moodysRating");

                    b.Property<int>("orderNumber");

                    b.Property<string>("sandPRating");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("WebApi.Models.RuleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descripton");

                    b.Property<string>("json");

                    b.Property<string>("name");

                    b.Property<string>("sqlPart");

                    b.Property<string>("sqlStr");

                    b.Property<string>("template");

                    b.HasKey("Id");

                    b.ToTable("Rule");
                });

            modelBuilder.Entity("WebApi.Models.TradeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("account");

                    b.Property<string>("benchmark");

                    b.Property<string>("book");

                    b.Property<double>("buyPrice");

                    b.Property<double>("buyQuantity");

                    b.Property<DateTime>("creationDate");

                    b.Property<string>("creationName");

                    b.Property<string>("dealName");

                    b.Property<string>("dealType");

                    b.Property<DateTime>("revisionDate");

                    b.Property<string>("revisionName");

                    b.Property<string>("security");

                    b.Property<double>("sellPrice");

                    b.Property<double>("sellQuantity");

                    b.Property<string>("side");

                    b.Property<string>("sourceListId");

                    b.Property<string>("status");

                    b.Property<DateTime>("tradeDate");

                    b.Property<string>("trader");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("WebApi.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("password");

                    b.Property<string>("role");

                    b.Property<string>("userName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
